'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAandR = 'TRUE'")>  _
        Public Property value1T() As String
            Get
                Return CType(Me("value1T"),String)
            End Get
            Set
                Me("value1T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAandR = 'FALSE'")>  _
        Public Property value1F() As String
            Get
                Return CType(Me("value1F"),String)
            End Get
            Set
                Me("value1F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAddInforOffice = 'TRUE'")>  _
        Public Property value2T() As String
            Get
                Return CType(Me("value2T"),String)
            End Get
            Set
                Me("value2T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAddInforOffice = 'FALSE'")>  _
        Public Property value2F() As String
            Get
                Return CType(Me("value2F"),String)
            End Get
            Set
                Me("value2F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAppAdmin = 'TRUE'")>  _
        Public Property value3T() As String
            Get
                Return CType(Me("value3T"),String)
            End Get
            Set
                Me("value3T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildAppAdmin = 'FALSE'")>  _
        Public Property value3F() As String
            Get
                Return CType(Me("value3F"),String)
            End Get
            Set
                Me("value3F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildCommands = 'TRUE'")>  _
        Public Property value4T() As String
            Get
                Return CType(Me("value4T"),String)
            End Get
            Set
                Me("value4T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildCommands = 'FALSE'")>  _
        Public Property value4F() As String
            Get
                Return CType(Me("value4F"),String)
            End Get
            Set
                Me("value4F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildCompMan = 'TRUE'")>  _
        Public Property value5T() As String
            Get
                Return CType(Me("value5T"),String)
            End Get
            Set
                Me("value5T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildCompMan = 'FALSE'")>  _
        Public Property value5F() As String
            Get
                Return CType(Me("value5F"),String)
            End Get
            Set
                Me("value5F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDashboard = 'TRUE'")>  _
        Public Property value6T() As String
            Get
                Return CType(Me("value6T"),String)
            End Get
            Set
                Me("value6T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDashboard = 'FALSE'")>  _
        Public Property value6F() As String
            Get
                Return CType(Me("value6F"),String)
            End Get
            Set
                Me("value6F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDesigner = 'TRUE'")>  _
        Public Property value7T() As String
            Get
                Return CType(Me("value7T"),String)
            End Get
            Set
                Me("value7T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDesigner = 'FALSE'")>  _
        Public Property value7F() As String
            Get
                Return CType(Me("value7F"),String)
            End Get
            Set
                Me("value7F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDesktop = 'TRUE'")>  _
        Public Property value8T() As String
            Get
                Return CType(Me("value8T"),String)
            End Get
            Set
                Me("value8T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDesktop = 'FALSE'")>  _
        Public Property value8F() As String
            Get
                Return CType(Me("value8F"),String)
            End Get
            Set
                Me("value8F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDeveloper = 'TRUE'")>  _
        Public Property value9T() As String
            Get
                Return CType(Me("value9T"),String)
            End Get
            Set
                Me("value9T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildDeveloper = 'FALSE'")>  _
        Public Property value9F() As String
            Get
                Return CType(Me("value9F"),String)
            End Get
            Set
                Me("value9F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildExcel = 'TRUE'")>  _
        Public Property value10T() As String
            Get
                Return CType(Me("value10T"),String)
            End Get
            Set
                Me("value10T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildExcel = 'FALSE'")>  _
        Public Property value10F() As String
            Get
                Return CType(Me("value10F"),String)
            End Get
            Set
                Me("value10F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildInput = 'TRUE'")>  _
        Public Property value11T() As String
            Get
                Return CType(Me("value11T"),String)
            End Get
            Set
                Me("value11T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildInput = 'FALSE'")>  _
        Public Property value11F() As String
            Get
                Return CType(Me("value11F"),String)
            End Get
            Set
                Me("value11F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildInstall = 'TRUE'")>  _
        Public Property value12T() As String
            Get
                Return CType(Me("value12T"),String)
            End Get
            Set
                Me("value12T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildInstall = 'FALSE'")>  _
        Public Property value12F() As String
            Get
                Return CType(Me("value12F"),String)
            End Get
            Set
                Me("value12F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildIntegration = 'TRUE'")>  _
        Public Property value13T() As String
            Get
                Return CType(Me("value13T"),String)
            End Get
            Set
                Me("value13T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildIntegration = 'FALSE'")>  _
        Public Property value13F() As String
            Get
                Return CType(Me("value13F"),String)
            End Get
            Set
                Me("value13F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildJEs = 'TRUE'")>  _
        Public Property value14T() As String
            Get
                Return CType(Me("value14T"),String)
            End Get
            Set
                Me("value14T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildJEs = 'FALSE'")>  _
        Public Property value14F() As String
            Get
                Return CType(Me("value14F"),String)
            End Get
            Set
                Me("value14F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildServerMan = 'TRUE'")>  _
        Public Property value15T() As String
            Get
                Return CType(Me("value15T"),String)
            End Get
            Set
                Me("value15T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildServerMan = 'FALSE'")>  _
        Public Property value15F() As String
            Get
                Return CType(Me("value15F"),String)
            End Get
            Set
                Me("value15F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxAdminMRP = 'TRUE'")>  _
        Public Property value16T() As String
            Get
                Return CType(Me("value16T"),String)
            End Get
            Set
                Me("value16T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxAdminMRP = 'FALSE'")>  _
        Public Property value16F() As String
            Get
                Return CType(Me("value16F"),String)
            End Get
            Set
                Me("value16F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxAdmin = 'TRUE'")>  _
        Public Property value17T() As String
            Get
                Return CType(Me("value17T"),String)
            End Get
            Set
                Me("value17T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxAdmin = 'FALSE'")>  _
        Public Property value17F() As String
            Get
                Return CType(Me("value17F"),String)
            End Get
            Set
                Me("value17F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxImp = 'TRUE'")>  _
        Public Property value18T() As String
            Get
                Return CType(Me("value18T"),String)
            End Get
            Set
                Me("value18T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxImp = 'FALSE'")>  _
        Public Property value18F() As String
            Get
                Return CType(Me("value18F"),String)
            End Get
            Set
                Me("value18F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxUserASC = 'TRUE'")>  _
        Public Property value19T() As String
            Get
                Return CType(Me("value19T"),String)
            End Get
            Set
                Me("value19T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxUserASC = 'FALSE'")>  _
        Public Property value19F() As String
            Get
                Return CType(Me("value19F"),String)
            End Get
            Set
                Me("value19F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxUserIAS = 'TRUE'")>  _
        Public Property value20T() As String
            Get
                Return CType(Me("value20T"),String)
            End Get
            Set
                Me("value20T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildTaxUserIAS = 'FALSE'")>  _
        Public Property value20F() As String
            Get
                Return CType(Me("value20F"),String)
            End Get
            Set
                Me("value20F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildWorkflow = 'TRUE'")>  _
        Public Property value21T() As String
            Get
                Return CType(Me("value21T"),String)
            End Get
            Set
                Me("value21T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildWorkflow = 'FALSE'")>  _
        Public Property value21F() As String
            Get
                Return CType(Me("value21F"),String)
            End Get
            Set
                Me("value21F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildReleaseNotes = 'TRUE'")>  _
        Public Property value22T() As String
            Get
                Return CType(Me("value22T"),String)
            End Get
            Set
                Me("value22T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildReleaseNotes = 'FALSE'")>  _
        Public Property value22F() As String
            Get
                Return CType(Me("value22F"),String)
            End Get
            Set
                Me("value22F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildUpgrade = 'TRUE'")>  _
        Public Property value23T() As String
            Get
                Return CType(Me("value23T"),String)
            End Get
            Set
                Me("value23T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vbuildUpgrade = 'FALSE'")>  _
        Public Property value23F() As String
            Get
                Return CType(Me("value23F"),String)
            End Get
            Set
                Me("value23F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vregression = 'TRUE'")>  _
        Public Property value24T() As String
            Get
                Return CType(Me("value24T"),String)
            End Get
            Set
                Me("value24T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Set vregression = 'FALSE'")>  _
        Public Property value24F() As String
            Get
                Return CType(Me("value24F"),String)
            End Get
            Set
                Me("value24F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value25T() As String
            Get
                Return CType(Me("value25T"),String)
            End Get
            Set
                Me("value25T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value25F() As String
            Get
                Return CType(Me("value25F"),String)
            End Get
            Set
                Me("value25F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value26T() As String
            Get
                Return CType(Me("value26T"),String)
            End Get
            Set
                Me("value26T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value26F() As String
            Get
                Return CType(Me("value26F"),String)
            End Get
            Set
                Me("value26F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value27T() As String
            Get
                Return CType(Me("value27T"),String)
            End Get
            Set
                Me("value27T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value27F() As String
            Get
                Return CType(Me("value27F"),String)
            End Get
            Set
                Me("value27F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value28T() As String
            Get
                Return CType(Me("value28T"),String)
            End Get
            Set
                Me("value28T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value28F() As String
            Get
                Return CType(Me("value28F"),String)
            End Get
            Set
                Me("value28F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value29T() As String
            Get
                Return CType(Me("value29T"),String)
            End Get
            Set
                Me("value29T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value29F() As String
            Get
                Return CType(Me("value29F"),String)
            End Get
            Set
                Me("value29F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value30T() As String
            Get
                Return CType(Me("value30T"),String)
            End Get
            Set
                Me("value30T") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property value30F() As String
            Get
                Return CType(Me("value30F"),String)
            End Get
            Set
                Me("value30F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\JTeng\Desktop\BuildAllPDFS.txt")>  _
        Public Property fileAddress() As String
            Get
                Return CType(Me("fileAddress"),String)
            End Get
            Set
                Me("fileAddress") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WindowsApplication1.My.MySettings
            Get
                Return Global.WindowsApplication1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
